name: "Space is the Place"
description: "Social and Geographic Influence in an Ever Evolving World" 

url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: pretty
highlighter: true
